name: Docker Build Publish

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
  release:
    types:
      - published
permissions: {}

jobs:
  build:
    name: Build
    permissions:
      actions: read
      contents: read
      checks: write
      id-token: write
      security-events: write
    uses: ./.github/workflows/_docker-build.yaml
    with:
      image-name: ob/docling-ob
      dockerfile: Dockerfile
      context: .
      provenance: false
    secrets: inherit