name: Docker Build Publish

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  release:
    types:
      - published
permissions: {}

jobs:
  build:
    name: Build amd64
    permissions:
      actions: read
      contents: read
      checks: write
      id-token: write
      security-events: write
    uses: Onebrief/actions/.github/workflows/reusable-docker-build.yml@main
    with:
      repository: onebrief/docling-ob
      dockerfile: Dockerfile
      context: .
      # Only build for amd64
      platforms: '[{"arch":"amd64","runner":"stepsecurity-x64"}]'
    secrets: inherit